---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/rio --version
    register: rio_test_output
  - name: rio --version
    debug:
      msg: '{{ rio_test_output.stdout }}'
